#include "common.hpp"
#include "ops/ops.h"
#include "ops_sycl.h"

namespace ggml_ops_ext::sycl { namespace {
struct s4{size_t v[4];}; template<typename T,typename G> class GridSampleKernel;
inline float unnorm(float v,int64_t z,bool a){return a?(v+1)*(z-1)*.5f:((v+1)*z-1)*.5f;}
inline float reflect(float v,int64_t z,bool a){float lo=a?0.f:-.5f,hi=a?float(z-1):float(z)-.5f,span=hi-lo;if(span<=0)return 0;v=::sycl::fabs(v-lo);float e=::sycl::fmod(v,span);int f=int(::sycl::floor(v/span));return(f&1?span-e:e)+lo;}
template<typename T> inline float sample(const T*i,int64_t x,int64_t y,int64_t c,int64_t n,ops_grid_sample_2d_desc d,s4 s){if(d.padding==ops_grid_padding_mode::border){x=x<0?0:(x>=d.input_width?d.input_width-1:x);y=y<0?0:(y>=d.input_height?d.input_height-1:y);}else if(x<0||x>=d.input_width||y<0||y>=d.input_height)return 0;return float(*reinterpret_cast<const T*>(reinterpret_cast<const char*>(i)+x*s.v[0]+y*s.v[1]+c*s.v[2]+n*s.v[3]));}
template<typename T,typename G> bool launch(::sycl::queue*q,ggml_tensor*o,const ggml_tensor*i,const ggml_tensor*g,ops_grid_sample_2d_desc d){s4 is={{i->nb[0],i->nb[1],i->nb[2],i->nb[3]}},gs={{g->nb[0],g->nb[1],g->nb[2],g->nb[3]}},os={{o->nb[0],o->nb[1],o->nb[2],o->nb[3]}};auto*ip=(const T*)i->data;auto*gp=(const G*)g->data;auto*op=(T*)o->data;int64_t total=ggml_nelements(o);q->submit([&](::sycl::handler&h){h.parallel_for<GridSampleKernel<T,G>>(::sycl::range<1>((size_t)total),[=](::sycl::id<1>id){int64_t v=id[0],ox=v%d.output_width;v/=d.output_width;int64_t oy=v%d.output_height;v/=d.output_height;int64_t c=v%d.channels,n=v/d.channels;size_t gb=ox*gs.v[1]+oy*gs.v[2]+n*gs.v[3];float x=unnorm(float(*reinterpret_cast<const G*>(reinterpret_cast<const char*>(gp)+gb)),d.input_width,d.align_corners),y=unnorm(float(*reinterpret_cast<const G*>(reinterpret_cast<const char*>(gp)+gb+gs.v[0])),d.input_height,d.align_corners);if(d.padding==ops_grid_padding_mode::reflection){x=::sycl::clamp(reflect(x,d.input_width,d.align_corners),0.f,float(d.input_width-1));y=::sycl::clamp(reflect(y,d.input_height,d.align_corners),0.f,float(d.input_height-1));}float r;if(d.mode==ops_grid_sample_mode::nearest)r=sample(ip,(int64_t)::sycl::rint(x),(int64_t)::sycl::rint(y),c,n,d,is);else{int64_t x0=(int64_t)::sycl::floor(x),y0=(int64_t)::sycl::floor(y);float wx=x-x0,wy=y-y0;r=sample(ip,x0,y0,c,n,d,is)*(1-wx)*(1-wy)+sample(ip,x0+1,y0,c,n,d,is)*wx*(1-wy)+sample(ip,x0,y0+1,c,n,d,is)*(1-wx)*wy+sample(ip,x0+1,y0+1,c,n,d,is)*wx*wy;}*reinterpret_cast<T*>(reinterpret_cast<char*>(op)+ox*os.v[0]+oy*os.v[1]+c*os.v[2]+n*os.v[3])=T(r);});});return true;}
template<typename T>bool grid(::sycl::queue*q,ggml_tensor*o,const ggml_tensor*i,const ggml_tensor*g,ops_grid_sample_2d_desc d){return g->type==GGML_TYPE_F32?launch<T,float>(q,o,i,g,d):g->type==GGML_TYPE_F16?launch<T,::sycl::half>(q,o,i,g,d):false;}
}
bool ggml_sycl_op_grid_sample_2d_entry(ggml_backend_t b,ggml_tensor*n){if(!n||!n->src[0]||!n->src[1])return false;ops_grid_sample_2d_params p{};memcpy(&p,n->op_params,sizeof(p));ggml_tensor*s[]={n->src[0],n->src[1]};ops_request r={ggml_backend_get_device(b),(int)n->op,s,2,&p,sizeof(p),n};ops_grid_sample_2d_desc d;if(!ops_validate_grid_sample_2d(r,&d))return false;auto*q=(::sycl::queue*)ggml_ops_ext_bridge_sycl_get_queue(b);switch(s[0]->type){case GGML_TYPE_F32:return grid<float>(q,n,s[0],s[1],d);case GGML_TYPE_F16:return grid<::sycl::half>(q,n,s[0],s[1],d);default:return false;}}
}
